#!/usr/bin/env python

import sys

fileNumber = sys.argv[1]
with open(sys.argv[2]) as f:
 s = f.readlines()
filename = s[int(fileNumber)]
with open("singleFile.txt", "w") as singleFile:
 singleFile.write(filename)
