#!/usr/bin/env python

import sys

fileNumber = sys.argv[1]
with open("htmlL581367.txt") as f:
 s = f.readlines()
filename = s[int(fileNumber)]
with open("singleFile.txt", "w") as singleFile:
 singleFile.write(filename)
